### ISSUE TITLE
duplicate stopwords_SK?

### ISSUE THREAD

**Issue by Alino** [SlovakNationalGallery/elasticsearch-slovencina#2]
I am not sure if this is unnecessary duplicate filter **stopwords_SK** or if there is some reason behind this in processing the words

```javascript
       "slovencina": {
          "type": "custom",
          "tokenizer": "standard",
          "filter": [
            "stopwords_SK",
            "lemmagen_filter_sk",
            "lowercase",
            "stopwords_SK",
            "asciifolding"
          ]
        }
```

**Comment by igor-kamil** [comment]
yes, there is a reason for that
because stopwords doesn't contain all possible variants of stopwords
so first step: remove the matched stopwords
second step: lemmatization
third step: remove the matched stopwords after lemmatization

it's well explained here -> https://www.zdrojak.cz/clanky/elasticsearch-vyhledavame-hezky-cesky-ii-a-taky-slovensky/

**Comment by Alino** [comment]
thank you!
